'use strict';

/**
 * Full zone data for all serviceable Kaduna neighbourhoods.
 * center: { lat, lng } — centroid of the area.
 * radiusKm: approximate coverage radius for the zone.
 * subAreas: known sub-neighbourhoods / streets within the zone.
 * senateDistrict: Kaduna State senatorial district.
 */

const KADUNA_ZONES = [
  {
    key: 'gra',
    name: 'GRA (Government Reserved Area)',
    localName: 'GRA',
    center: { lat: 10.5218, lng: 7.4512 },
    radiusKm: 2.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['GRA Phase 1', 'GRA Phase 2', 'GRA Phase 3', 'Officers Mess Area'],
  },
  {
    key: 'barnawa',
    name: 'Barnawa',
    localName: 'Barnawa',
    center: { lat: 10.4872, lng: 7.4453 },
    radiusKm: 3.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Barnawa Phase 1', 'Barnawa Phase 2', 'Barnawa Phase 3', 'Barnawa Low Cost'],
  },
  {
    key: 'malali',
    name: 'Malali',
    localName: 'Malali',
    center: { lat: 10.5712, lng: 7.4221 },
    radiusKm: 2.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna North',
    subAreas: ['Malali GRA', 'Malali Extension', 'Army Barracks Malali'],
  },
  {
    key: 'tudun_wada',
    name: 'Tudun Wada',
    localName: 'Tudun Wada',
    center: { lat: 10.5332, lng: 7.4231 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Tudun Wada North', 'Tudun Wada South', 'Tudun Wada Central'],
  },
  {
    key: 'narayi',
    name: 'Narayi',
    localName: 'Narayi',
    center: { lat: 10.5015, lng: 7.4102 },
    radiusKm: 2.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Narayi High Cost', 'Narayi Low Cost', 'Narayi Extension'],
  },
  {
    key: 'kabala_west',
    name: 'Kabala West',
    localName: 'Kabala Yamma',
    center: { lat: 10.5412, lng: 7.3981 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Kabala West Phase 1', 'Kabala West Phase 2'],
  },
  {
    key: 'kabala_east',
    name: 'Kabala East',
    localName: 'Kabala Gabas',
    center: { lat: 10.5452, lng: 7.4121 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Kabala East Phase 1', 'Kabala East Phase 2', 'Kabala Costain'],
  },
  {
    key: 'ungwan_rimi',
    name: "Ungwan Rimi",
    localName: "Unguwar Rimi",
    center: { lat: 10.5561, lng: 7.4321 },
    radiusKm: 1.8,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ["Ungwan Rimi GRA", "Ungwan Rimi Low Cost"],
  },
  {
    key: 'ungwan_sarki',
    name: "Ungwan Sarki",
    localName: "Unguwar Sarki",
    center: { lat: 10.5641, lng: 7.4481 },
    radiusKm: 1.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ["Ungwan Sarki North", "Ungwan Sarki South"],
  },
  {
    key: 'kaura',
    name: 'Kaura',
    localName: 'Kaura',
    center: { lat: 10.5214, lng: 7.4831 },
    radiusKm: 3.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Kaura Extension', 'Kaura Housing Estate', 'Shell Cooperative Estate'],
  },
  {
    key: 'chikun',
    name: 'Chikun',
    localName: 'Chikun',
    center: { lat: 10.4612, lng: 7.3821 },
    radiusKm: 4.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Chikun Village', 'Chikun LGA Headquarters'],
  },
  {
    key: 'rigachikun',
    name: 'Rigachikun',
    localName: 'Rigachikun',
    center: { lat: 10.6021, lng: 7.3521 },
    radiusKm: 3.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna North',
    subAreas: ['Rigachikun Layout', 'Rigachikun Extension', 'Rigachikun Quarters'],
  },
  {
    key: 'sabon_tasha',
    name: 'Sabon Tasha',
    localName: 'Sabon Tasha',
    center: { lat: 10.4781, lng: 7.4721 },
    radiusKm: 2.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Sabon Tasha Market', 'Sabon Tasha Layout', 'Sabon Tasha Extension'],
  },
  {
    key: 'tudun_nupawa',
    name: 'Tudun Nupawa',
    localName: 'Tudun Nupawa',
    center: { lat: 10.5181, lng: 7.4321 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Tudun Nupawa Phase 1', 'Tudun Nupawa Phase 2'],
  },
  {
    key: 'gonin_gora',
    name: 'Gonin Gora',
    localName: 'Gonin Gora',
    center: { lat: 10.4521, lng: 7.4091 },
    radiusKm: 2.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Gonin Gora Phase 1', 'Gonin Gora Phase 2', 'Gonin Gora Phase 3'],
  },
  {
    key: 'kakuri',
    name: 'Kakuri',
    localName: 'Kakuri',
    center: { lat: 10.4851, lng: 7.4321 },
    radiusKm: 3.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Kakuri Market', 'Kakuri Layout', 'Kakuri Industrial Area', 'Kakuri Village'],
  },
  {
    key: 'badiko',
    name: 'Badiko',
    localName: 'Badiko',
    center: { lat: 10.5721, lng: 7.3891 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna North',
    subAreas: ['Badiko Layout', 'Badiko Extension'],
  },
  {
    key: 'ungwan_dosa',
    name: "Ungwan Dosa",
    localName: "Unguwar Dosa",
    center: { lat: 10.5681, lng: 7.4651 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna North',
    subAreas: ["Ungwan Dosa Low Cost", "Ungwan Dosa Phase 2"],
  },
  {
    key: 'makera',
    name: 'Makera',
    localName: 'Makera',
    center: { lat: 10.5081, lng: 7.4551 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Makera Asabe', 'Makera Layout'],
  },
  {
    key: 'romi',
    name: 'Romi',
    localName: 'Romi',
    center: { lat: 10.4942, lng: 7.3821 },
    radiusKm: 2.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Romi Housing Estate', 'Romi Extension', 'Romi New Extension'],
  },
  {
    key: 'sabo_gari',
    name: 'Sabo Gari',
    localName: 'Sabon Gari',
    center: { lat: 10.5311, lng: 7.4681 },
    radiusKm: 1.8,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Sabo Gari Market', 'Sabo Gari Quarters'],
  },
  {
    key: 'nasarawa',
    name: 'Nasarawa',
    localName: 'Nasarawa',
    center: { lat: 10.5581, lng: 7.4781 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Nasarawa GRA', 'Nasarawa Extension'],
  },
  {
    key: 'ungwan_muazu',
    name: "Ungwan Muazu",
    localName: "Unguwar Muazu",
    center: { lat: 10.5451, lng: 7.4621 },
    radiusKm: 1.5,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ["Ungwan Muazu Phase 1"],
  },
  {
    key: 'television',
    name: 'Television',
    localName: 'Television',
    center: { lat: 10.5351, lng: 7.4041 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Television Layout', 'Television Phase 2', 'Television Extension'],
  },
  {
    key: 'abakpa',
    name: 'Abakpa',
    localName: 'Abakpa',
    center: { lat: 10.5181, lng: 7.4251 },
    radiusKm: 2.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna Central',
    subAreas: ['Abakpa Phase 1', 'Abakpa Phase 2', 'Abakpa Extension'],
  },
  {
    key: 'kudenda',
    name: 'Kudenda',
    localName: 'Kudenda',
    center: { lat: 10.4411, lng: 7.4521 },
    radiusKm: 3.0,
    isActive: true,
    isServiceable: true,
    senateDistrict: 'Kaduna South',
    subAreas: ['Kudenda Industrial Layout', 'Kudenda Village', 'New Kudenda Estate'],
  },
];

module.exports = KADUNA_ZONES;
