'use strict';

/**
 * Firestore service type documents to seed into the 'services' collection.
 * These correspond 1:1 with the SERVICE_TYPES and SERVICE_PRICING constants.
 */

const SERVICE_TYPE_DOCS = [
  {
    key: 'standard_clean',
    label: 'Standard Clean',
    description: 'Regular home cleaning — sweeping, mopping, surface wipe, bathroom, kitchen.',
    longDescription:
      'Our standard clean covers all the basics your home needs to stay fresh. Includes sweeping and mopping all floors, wiping down surfaces and countertops, cleaning bathrooms (toilet, sink, bathtub/shower), and tidying the kitchen.',
    minPrice: 8000,
    maxPrice: 15000,
    estimatedHours: { min: 2, max: 4 },
    currency: 'NGN',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['laundry', 'ironing'],
    imageUrl: null,
    sortOrder: 1,
    popularityScore: 100,
    tags: ['cleaning', 'home', 'regular'],
  },
  {
    key: 'deep_clean',
    label: 'Deep Clean',
    description: 'Thorough cleaning including inside cupboards, appliances, walls, and tiles.',
    longDescription:
      'A deep clean tackles the dirt that regular cleaning misses. Includes everything in the standard clean plus inside cupboards and wardrobes, appliance interiors (fridge, oven, microwave), wall scrubbing, tile and grout cleaning, under-furniture cleaning, and detailed bathroom descaling.',
    minPrice: 18000,
    maxPrice: 35000,
    estimatedHours: { min: 4, max: 8 },
    currency: 'NGN',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['windows', 'fridge', 'oven'],
    imageUrl: null,
    sortOrder: 2,
    popularityScore: 80,
    tags: ['cleaning', 'deep', 'thorough', 'home'],
  },
  {
    key: 'harmattan_package',
    label: 'Harmattan Package',
    description: 'Seasonal deep dust removal — ceiling fans, curtains, furniture, floor scrubbing.',
    longDescription:
      'The Harmattan Package is specifically designed for Nigeria\'s harmattan season when red dust coats every surface. Includes ceiling fan blades, curtain removal and dusting, upholstered furniture vacuuming and wiping, complete floor scrubbing with anti-dust treatment, and all surfaces wiped down twice.',
    minPrice: 12000,
    maxPrice: 22000,
    estimatedHours: { min: 3, max: 6 },
    currency: 'NGN',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['windows', 'laundry'],
    imageUrl: null,
    sortOrder: 3,
    popularityScore: 70,
    tags: ['harmattan', 'seasonal', 'dust', 'cleaning'],
  },
  {
    key: 'post_event',
    label: 'Post-Event Clean',
    description: 'Heavy-duty cleanup after parties, weddings, and celebrations.',
    longDescription:
      'After the celebration comes the cleanup. Our post-event team handles the heavy lifting: collecting and disposing of trash, washing and stacking dishes and cutlery, scrubbing food stains from floors and walls, cleaning outdoor spaces, restoring furniture arrangement, and leaving your venue spotless.',
    minPrice: 20000,
    maxPrice: 40000,
    estimatedHours: { min: 4, max: 10 },
    currency: 'NGN',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['laundry', 'ironing'],
    imageUrl: null,
    sortOrder: 4,
    popularityScore: 60,
    tags: ['event', 'party', 'wedding', 'post-event', 'cleaning'],
  },
  {
    key: 'monthly_subscription',
    label: 'Monthly Subscription',
    description: '4 standard cleans per month at a discounted rate.',
    longDescription:
      'Subscribe and save! Get 4 standard cleaning sessions per month at a discounted rate compared to booking individually. Priority scheduling, the same cleaner each time (where possible), and a dedicated account manager.',
    minPrice: 25000,
    maxPrice: 45000,
    estimatedHours: { min: 2, max: 4 },
    currency: 'NGN',
    billingCycle: 'monthly',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['laundry', 'ironing'],
    imageUrl: null,
    sortOrder: 5,
    popularityScore: 90,
    tags: ['subscription', 'monthly', 'regular', 'discount'],
  },
  {
    key: 'corporate',
    label: 'Corporate / Office Clean',
    description: 'Custom pricing for offices and commercial spaces. Contact for quote.',
    longDescription:
      'We provide reliable office and commercial cleaning services for businesses in Kaduna. Services include daily, weekly, or one-off cleans customised to your office layout and requirements. Pricing is bespoke — contact us for a free site assessment and quote.',
    minPrice: 30000,
    maxPrice: null,
    estimatedHours: { min: 3, max: 16 },
    currency: 'NGN',
    requiresQuote: true,
    isActive: true,
    availableAddOns: ['windows'],
    imageUrl: null,
    sortOrder: 6,
    popularityScore: 50,
    tags: ['corporate', 'office', 'commercial', 'business'],
  },
  {
    key: 'laundry',
    label: 'Laundry',
    description: 'Wash, dry, and fold service. Priced per kg.',
    longDescription:
      'Drop off your laundry and we\'ll wash, dry, and fold it for you. Priced per kilogram. Includes sorting by colour, gentle wash for delicates, and neat folding. We handle clothing, bedsheets, and towels. Minimum charge: ₦500.',
    minPrice: 500,
    maxPrice: 5000,
    currency: 'NGN',
    unit: 'per_kg',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['ironing'],
    imageUrl: null,
    sortOrder: 7,
    popularityScore: 65,
    tags: ['laundry', 'wash', 'fold'],
  },
  {
    key: 'ironing',
    label: 'Ironing',
    description: 'Professional ironing service. Priced per item.',
    longDescription:
      'Get your clothes ironed by professionals. Priced per item. We handle shirts, trousers, dresses, agbadas, and more. Fabrics treated with appropriate heat settings.',
    minPrice: 200,
    maxPrice: 3000,
    currency: 'NGN',
    unit: 'per_item',
    requiresQuote: false,
    isActive: true,
    availableAddOns: [],
    imageUrl: null,
    sortOrder: 8,
    popularityScore: 55,
    tags: ['ironing', 'clothes', 'pressing'],
  },
  {
    key: 'window_cleaning',
    label: 'Window Cleaning',
    description: 'Interior and exterior window wash.',
    longDescription:
      'Crystal-clear windows make a huge difference. Our window cleaning service covers interior and exterior window panes, frames, and sills. We use squeegees and streak-free solution for a professional finish.',
    minPrice: 5000,
    maxPrice: 15000,
    currency: 'NGN',
    requiresQuote: false,
    isActive: true,
    availableAddOns: [],
    imageUrl: null,
    sortOrder: 9,
    popularityScore: 45,
    tags: ['windows', 'glass', 'exterior', 'cleaning'],
  },
  {
    key: 'move_in_out',
    label: 'Move-In / Move-Out Clean',
    description: 'Complete cleaning for vacated or newly occupied homes.',
    longDescription:
      'Moving is stressful enough — let us handle the cleaning. Our move-in/move-out service ensures the property is spotless for handover or new occupancy. Includes every room, inside all fixtures, walls, floors, bathrooms, kitchen, and outdoor areas. Deep clean guaranteed.',
    minPrice: 20000,
    maxPrice: 50000,
    estimatedHours: { min: 5, max: 12 },
    currency: 'NGN',
    requiresQuote: false,
    isActive: true,
    availableAddOns: ['windows', 'fridge', 'oven'],
    imageUrl: null,
    sortOrder: 10,
    popularityScore: 40,
    tags: ['moving', 'handover', 'tenancy', 'deep-clean'],
  },
];

module.exports = SERVICE_TYPE_DOCS;
