import { Colors } from './colors';

export const SERVICE_TYPES = {
  REGULAR_CLEANING: 'regular_cleaning',
  DEEP_CLEANING: 'deep_cleaning',
  POST_CONSTRUCTION: 'post_construction',
  MOVE_IN_OUT: 'move_in_out',
  LAUNDRY: 'laundry',
  CARPET_SOFA: 'carpet_sofa',
  OFFICE_CLEANING: 'office_cleaning',
  WINDOW_CLEANING: 'window_cleaning',
};

export const SERVICES = [
  {
    id: SERVICE_TYPES.REGULAR_CLEANING,
    icon: 'home-variant',
    emoji: '🏠',
    color: Colors.primary,
    bgColor: Colors.primaryFaded,
    basePrice: 5000,
    priceUnit: 'per session',
    durationHours: 3,
    popular: true,
    nameKey: 'services.regularCleaning',
    descKey: 'services.regularCleaningDesc',
    includes: [
      'services.includes.dusting',
      'services.includes.vacuuming',
      'services.includes.mopping',
      'services.includes.bathroom',
      'services.includes.kitchen',
    ],
    extras: [
      { id: 'inside_fridge', labelKey: 'services.extras.insideFridge', price: 1000 },
      { id: 'inside_oven', labelKey: 'services.extras.insideOven', price: 1500 },
      { id: 'inside_cabinets', labelKey: 'services.extras.insideCabinets', price: 2000 },
    ],
  },
  {
    id: SERVICE_TYPES.DEEP_CLEANING,
    icon: 'spray-bottle',
    emoji: '✨',
    color: Colors.secondary,
    bgColor: Colors.secondaryFaded,
    basePrice: 12000,
    priceUnit: 'per session',
    durationHours: 6,
    popular: true,
    nameKey: 'services.deepCleaning',
    descKey: 'services.deepCleaningDesc',
    includes: [
      'services.includes.everythingInRegular',
      'services.includes.deepScrub',
      'services.includes.insideAppliances',
      'services.includes.windowInterior',
      'services.includes.baseboards',
    ],
    extras: [
      { id: 'exterior_windows', labelKey: 'services.extras.exteriorWindows', price: 3000 },
      { id: 'garage', labelKey: 'services.extras.garage', price: 2500 },
    ],
  },
  {
    id: SERVICE_TYPES.POST_CONSTRUCTION,
    icon: 'hard-hat',
    emoji: '🏗️',
    color: '#795548',
    bgColor: '#EFEBE9',
    basePrice: 25000,
    priceUnit: 'per session',
    durationHours: 8,
    popular: false,
    nameKey: 'services.postConstruction',
    descKey: 'services.postConstructionDesc',
    includes: [
      'services.includes.dustRemoval',
      'services.includes.paintSplatters',
      'services.includes.cementStains',
      'services.includes.windowPolish',
      'services.includes.floorStrip',
    ],
    extras: [],
  },
  {
    id: SERVICE_TYPES.MOVE_IN_OUT,
    icon: 'truck-moving',
    emoji: '📦',
    color: Colors.accent,
    bgColor: Colors.accentFaded,
    basePrice: 15000,
    priceUnit: 'per session',
    durationHours: 5,
    popular: false,
    nameKey: 'services.moveInOut',
    descKey: 'services.moveInOutDesc',
    includes: [
      'services.includes.fullDeepClean',
      'services.includes.insideAllCabinets',
      'services.includes.applianceCleaning',
      'services.includes.wallWipe',
    ],
    extras: [],
  },
  {
    id: SERVICE_TYPES.LAUNDRY,
    icon: 'washing-machine',
    emoji: '👕',
    color: '#0097A7',
    bgColor: '#E0F7FA',
    basePrice: 3000,
    priceUnit: 'per load',
    durationHours: 2,
    popular: false,
    nameKey: 'services.laundry',
    descKey: 'services.laundryDesc',
    includes: [
      'services.includes.wash',
      'services.includes.dryFold',
      'services.includes.ironing',
    ],
    extras: [
      { id: 'dry_cleaning', labelKey: 'services.extras.dryCleaning', price: 5000 },
      { id: 'stain_treatment', labelKey: 'services.extras.stainTreatment', price: 1000 },
    ],
  },
  {
    id: SERVICE_TYPES.CARPET_SOFA,
    icon: 'sofa',
    emoji: '🛋️',
    color: '#6A1B9A',
    bgColor: '#F3E5F5',
    basePrice: 8000,
    priceUnit: 'per session',
    durationHours: 3,
    popular: false,
    nameKey: 'services.carpetSofa',
    descKey: 'services.carpetSofaDesc',
    includes: [
      'services.includes.deepShampoo',
      'services.includes.stainRemoval',
      'services.includes.drying',
    ],
    extras: [
      { id: 'extra_sofa', labelKey: 'services.extras.extraSofa', price: 3000 },
      { id: 'extra_carpet', labelKey: 'services.extras.extraCarpet', price: 2000 },
    ],
  },
  {
    id: SERVICE_TYPES.OFFICE_CLEANING,
    icon: 'office-building',
    emoji: '🏢',
    color: Colors.secondary,
    bgColor: Colors.secondaryFaded,
    basePrice: 20000,
    priceUnit: 'per visit',
    durationHours: 4,
    popular: false,
    nameKey: 'services.officeCleaning',
    descKey: 'services.officeCleaningDesc',
    includes: [
      'services.includes.desksChairs',
      'services.includes.floors',
      'services.includes.toilets',
      'services.includes.kitchenette',
      'services.includes.reception',
    ],
    extras: [
      { id: 'after_hours', labelKey: 'services.extras.afterHours', price: 5000 },
    ],
  },
  {
    id: SERVICE_TYPES.WINDOW_CLEANING,
    icon: 'window-maximize',
    emoji: '🪟',
    color: '#00838F',
    bgColor: '#E0F7FA',
    basePrice: 6000,
    priceUnit: 'per session',
    durationHours: 2,
    popular: false,
    nameKey: 'services.windowCleaning',
    descKey: 'services.windowCleaningDesc',
    includes: [
      'services.includes.interiorWindows',
      'services.includes.windowSills',
      'services.includes.tracks',
    ],
    extras: [
      { id: 'exterior', labelKey: 'services.extras.exteriorWindows', price: 4000 },
    ],
  },
];

export const getServiceById = (id) => SERVICES.find((s) => s.id === id);

export const getPopularServices = () => SERVICES.filter((s) => s.popular);

export const formatPrice = (price) => `₦${price.toLocaleString('en-NG')}`;

export default SERVICES;
